### ISSUE TITLE
WIFI PROBLEM 

### ISSUE THREAD

**Issue by Hdehjeke** [TejasKamat/mojito_releases#2]
After installing this new version of evolution x V8.2  The Wifi is not turning on...is there any solution??

Uploading screen-20240122-122413.mp4…

**Comment by TejasKamat** [comment]
> After installing this new version of evolution x V8.2 The Wifi is not turning on...is there any solution??
> 
> Uploading screen-20240122-122413.mp4…

Hey, you didn't followed the proper instructions, kindly flash 14.0.8.0 firmware, your WiFi issue will be fixed. 

Have a great day.

**Comment by Hdehjeke** [comment]
Yes it worked after I flashed it....thanks
